### ISSUE TITLE
azurewadtable - not getting any data pulled out

### ISSUE THREAD

**Issue by Joffinn** [Azure/azure-diagnostics-tools#112]
Hi,

We have our logs in azure cloud, so far we were using linqpad to read them.
I'm setting up ELK so we could analyse them in a more effective way.

following all instruction for https://github.com/Azure/azure-diagnostics-tools/tree/master/Logstash/logstash-input-azurewadtable I'm still unable to get any data.

I changed the collection start time for a date in past, still nothing more than what is below.

```
C:\Users\username>cd c:\ELK\logstash-5.6.3\bin

c:\ELK\logstash-5.6.3\bin>logstash -f logstash-wad.conf
c:/ELK/logstash-5.6.3/vendor/bundle/jruby/1.9/gems/manticore-0.6.1-java/lib/manticore/client.rb:108 warning: already initialized constant DEFAULT_MAX_POOL_SIZE
c:/ELK/logstash-5.6.3/vendor/bundle/jruby/1.9/gems/manticore-0.6.1-java/lib/manticore/client.rb:110 warning: already initialized constant DEFAULT_REQUEST_TIMEOUT
c:/ELK/logstash-5.6.3/vendor/bundle/jruby/1.9/gems/manticore-0.6.1-java/lib/manticore/client.rb:111 warning: already initialized constant DEFAULT_SOCKET_TIMEOUT
c:/ELK/logstash-5.6.3/vendor/bundle/jruby/1.9/gems/manticore-0.6.1-java/lib/manticore/client.rb:112 warning: already initialized constant DEFAULT_CONNECT_TIMEOUT
c:/ELK/logstash-5.6.3/vendor/bundle/jruby/1.9/gems/manticore-0.6.1-java/lib/manticore/client.rb:113 warning: already initialized constant DEFAULT_MAX_REDIRECTS
c:/ELK/logstash-5.6.3/vendor/bundle/jruby/1.9/gems/manticore-0.6.1-java/lib/manticore/client.rb:114 warning: already initialized constant DEFAULT_EXPECT_CONTINUE
c:/ELK/logstash-5.6.3/vendor/bundle/jruby/1.9/gems/manticore-0.6.1-java/lib/manticore/client.rb:115 warning: already initialized constant DEFAULT_STALE_CHECK
c:/ELK/logstash-5.6.3/vendor/bundle/jruby/1.9/gems/manticore-0.6.1-java/lib/manticore/client.rb:590 warning: already initialized constant ISO_8859_1
c:/ELK/logstash-5.6.3/vendor/bundle/jruby/1.9/gems/manticore-0.6.1-java/lib/manticore/client.rb:641 warning: already initialized constant KEY_EXTRACTION_REGEXP
Sending Logstash's logs to c:/ELK/logstash-5.6.3/logs which is now configured via log4j2.properties
[2017-10-18T10:23:24,946][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"fb_apache", :directory=>"c:/ELK/logstash-5.6.3/modules/fb_apache/configuration"}
[2017-10-18T10:23:24,950][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"netflow", :directory=>"c:/ELK/logstash-5.6.3/modules/netflow/configuration"}
[2017-10-18T10:23:26,107][INFO ][logstash.inputs.azurewadtable] Using version 0.9.x input plugin 'azurewadtable'. This plugin should work but would benefit from use by folks like you. Please let us know if you find bugs or have suggestions on how to improve this plugin.
[2017-10-18T10:23:26,149][INFO ][logstash.pipeline        ] Starting pipeline {"id"=>"main", "pipeline.workers"=>4, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>500}
[2017-10-18T10:24:41,778][INFO ][logstash.pipeline        ] Pipeline main started
[2017-10-18T10:24:41,982][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
```

Am I totally missing something here?

**Comment by Joffinn** [comment]
FYI my config file looks like this:

```
input {
  azurewadtable {
    account_name => "STORAGE ACCOUNT NAME"
    access_key => "STORAGE ACCESS KEY"
    table_name => "TABLE NAME"
  }
}
output {
  elasticsearch {
    hosts => "[10.0.2.100:9200]"
    index => "wad"

  }
}

```

my guess is that I did something wrong with output but I don't see what.

**Comment by xiaomi7732** [comment]
@Joffinn ,
Firstly, please try the simplest debug output like this to see if you can see the output:
```yaml
output {
    stdout { 
        codec => rubydebug
    }
}
```
If yes, then, try elasticsearch output plugin with default index:
```yaml
output {
  elasticsearch {
    hosts => "[10.0.2.100:9200]"
  }
}
```
If you do want to customize index, give it a hard-coded value will not take you anywhere. Please refer the document here to setup the index parameter:
https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-index.

**Comment by xiaomi7732** [comment]
@Joffinn,
It has been a while, did you get any chance to try the bare-bone configuration out?

**Comment by Joffinn** [comment]
@xiaomi7732 a colleague of mine found the trick to make it run.
We had to comment the azurewadtable.rb file line 81 such as 
`    #for i in 0..99
    #  query_filter << " or (PartitionKey gt '#{i.to_s.rjust(19, '0')}___#{partitionkey_from_datetime(@last_timestamp)}' and PartitionKey lt '#{i.to_s.rjust(19, '0')}___#{partitionkey_from_datetime(@until_timestamp)}')"
    #end # for block`
And suddenly it worked like a charm

She found this from some other thread but we still didn't understand why we needed to do so in order to have the plugin running properly.

**Comment by xiaomi7732** [comment]
@Joffinn,
Really appreciate your input!
@clguimanMSFT,
Could you please follow up a bit on this issue?

**Comment by clguimanMSFT** [comment]
@Joffinn The commented out lines just extend the query to include more types of data. Sometimes the partition key can also include <number>_timestamp.
Is it possible to share some of the data in the tables? The PartitionKey column is enough. You can use Storage Explorer (https://azure.microsoft.com/en-us/features/storage-explorer/) to get this data

**Comment by Joffinn** [comment]
@clguimanMSFT atm I only have access to these tables through LinqPad
But PartitionKey column looks like this
Hope it helps

`

0636441762000000000
--
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441768000000000
0636441768000000000
0636441768000000000
0636441768000000000
0636441768000000000
0636441768000000000
0636441768000000000
0636441768000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000

0636441762000000000
--
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441762000000000
0636441768000000000
0636441768000000000
0636441768000000000
0636441768000000000
0636441768000000000
0636441768000000000
0636441768000000000
0636441768000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000
0636441774000000000


`

**Comment by clguimanMSFT** [comment]
@Joffinn Can you please set the log level to 'debug' and capture the traces emmited by the azurewadtable plugin?
It should at least include the full query, any exceptions and anything before "[filter_duplicates] ... new item"

**Comment by Joffinn** [comment]
@clguimanMSFT that's what I get when running in debug mode (and without commenting azurewadtable.rb file)

`PS C:\ELK\logstash-5.6.3\bin> .\logstash -f .\logstash-wad.conf --log.level=debug
Sending Logstash's logs to C:/ELK/logstash-5.6.3/logs which is now configured via log4j2.properties
[2017-11-03T12:49:12,852][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"fb_apache", :directory=>"C:/ELK/logstash-5.6.3/modules/fb_apache/configuration"}
[2017-11-03T12:49:12,871][DEBUG][logstash.plugins.registry] Adding plugin to the registry {:name=>"fb_apache", :type=>:modules, :class=>#<LogStash::Modules::Scaffold:0xcd38b34 @kibana_version_parts=["5", "6", "0"], @module_name="fb_apach
e", @directory="C:/ELK/logstash-5.6.3/modules/fb_apache/configuration">}
[2017-11-03T12:49:12,873][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"netflow", :directory=>"C:/ELK/logstash-5.6.3/modules/netflow/configuration"}
[2017-11-03T12:49:12,875][DEBUG][logstash.plugins.registry] Adding plugin to the registry {:name=>"netflow", :type=>:modules, :class=>#<LogStash::Modules::Scaffold:0x3152e106 @kibana_version_parts=["5", "6", "0"], @module_name="netflow",
 @directory="C:/ELK/logstash-5.6.3/modules/netflow/configuration">}
[2017-11-03T12:49:12,914][DEBUG][logstash.runner          ] -------- Logstash Settings (* means modified) ---------
[2017-11-03T12:49:12,914][DEBUG][logstash.runner          ] node.name: "LAPTOP0109"
[2017-11-03T12:49:12,915][DEBUG][logstash.runner          ] *path.config: ".\\logstash-wad.conf"
[2017-11-03T12:49:12,915][DEBUG][logstash.runner          ] path.data: "C:/ELK/logstash-5.6.3/data"
[2017-11-03T12:49:12,916][DEBUG][logstash.runner          ] modules.cli: []
[2017-11-03T12:49:12,916][DEBUG][logstash.runner          ] modules: []
[2017-11-03T12:49:12,916][DEBUG][logstash.runner          ] modules_setup: false
[2017-11-03T12:49:12,916][DEBUG][logstash.runner          ] config.test_and_exit: false
[2017-11-03T12:49:12,917][DEBUG][logstash.runner          ] config.reload.automatic: false
[2017-11-03T12:49:12,918][DEBUG][logstash.runner          ] config.support_escapes: false
[2017-11-03T12:49:12,918][DEBUG][logstash.runner          ] config.reload.interval: 3
[2017-11-03T12:49:12,919][DEBUG][logstash.runner          ] metric.collect: true
[2017-11-03T12:49:12,919][DEBUG][logstash.runner          ] pipeline.id: "main"
[2017-11-03T12:49:12,922][DEBUG][logstash.runner          ] pipeline.system: false
[2017-11-03T12:49:12,922][DEBUG][logstash.runner          ] pipeline.workers: 4
[2017-11-03T12:49:12,923][DEBUG][logstash.runner          ] pipeline.output.workers: 1
[2017-11-03T12:49:12,924][DEBUG][logstash.runner          ] pipeline.batch.size: 125
[2017-11-03T12:49:12,925][DEBUG][logstash.runner          ] pipeline.batch.delay: 5
[2017-11-03T12:49:12,925][DEBUG][logstash.runner          ] pipeline.unsafe_shutdown: false
[2017-11-03T12:49:12,926][DEBUG][logstash.runner          ] path.plugins: []
[2017-11-03T12:49:12,926][DEBUG][logstash.runner          ] config.debug: false
[2017-11-03T12:49:12,926][DEBUG][logstash.runner          ] *log.level: "debug" (default: "info")
[2017-11-03T12:49:12,926][DEBUG][logstash.runner          ] version: false
[2017-11-03T12:49:12,926][DEBUG][logstash.runner          ] help: false
[2017-11-03T12:49:12,927][DEBUG][logstash.runner          ] log.format: "plain"
[2017-11-03T12:49:12,927][DEBUG][logstash.runner          ] http.host: "127.0.0.1"
[2017-11-03T12:49:12,927][DEBUG][logstash.runner          ] http.port: 9600..9700
[2017-11-03T12:49:12,929][DEBUG][logstash.runner          ] http.environment: "production"
[2017-11-03T12:49:12,930][DEBUG][logstash.runner          ] queue.type: "memory"
[2017-11-03T12:49:12,931][DEBUG][logstash.runner          ] queue.drain: false
[2017-11-03T12:49:12,931][DEBUG][logstash.runner          ] queue.page_capacity: 262144000
[2017-11-03T12:49:12,931][DEBUG][logstash.runner          ] queue.max_bytes: 1073741824
[2017-11-03T12:49:12,931][DEBUG][logstash.runner          ] queue.max_events: 0
[2017-11-03T12:49:12,931][DEBUG][logstash.runner          ] queue.checkpoint.acks: 1024
[2017-11-03T12:49:12,932][DEBUG][logstash.runner          ] queue.checkpoint.writes: 1024
[2017-11-03T12:49:12,932][DEBUG][logstash.runner          ] queue.checkpoint.interval: 1000
[2017-11-03T12:49:12,932][DEBUG][logstash.runner          ] dead_letter_queue.enable: false
[2017-11-03T12:49:12,932][DEBUG][logstash.runner          ] dead_letter_queue.max_bytes: 1073741824
[2017-11-03T12:49:12,934][DEBUG][logstash.runner          ] slowlog.threshold.warn: -1
[2017-11-03T12:49:12,935][DEBUG][logstash.runner          ] slowlog.threshold.info: -1
[2017-11-03T12:49:12,935][DEBUG][logstash.runner          ] slowlog.threshold.debug: -1
[2017-11-03T12:49:12,935][DEBUG][logstash.runner          ] slowlog.threshold.trace: -1
[2017-11-03T12:49:12,936][DEBUG][logstash.runner          ] path.queue: "C:/ELK/logstash-5.6.3/data/queue"
[2017-11-03T12:49:12,936][DEBUG][logstash.runner          ] path.dead_letter_queue: "C:/ELK/logstash-5.6.3/data/dead_letter_queue"
[2017-11-03T12:49:12,936][DEBUG][logstash.runner          ] path.settings: "C:/ELK/logstash-5.6.3/config"
[2017-11-03T12:49:12,937][DEBUG][logstash.runner          ] path.logs: "C:/ELK/logstash-5.6.3/logs"
[2017-11-03T12:49:12,937][DEBUG][logstash.runner          ] --------------- Logstash Settings -------------------
[2017-11-03T12:49:12,977][DEBUG][logstash.agent           ] Agent: Configuring metric collection
[2017-11-03T12:49:12,983][DEBUG][logstash.instrument.periodicpoller.os] PeriodicPoller: Starting {:polling_interval=>5, :polling_timeout=>120}
[2017-11-03T12:49:13,013][DEBUG][logstash.instrument.periodicpoller.jvm] PeriodicPoller: Starting {:polling_interval=>5, :polling_timeout=>120}
[2017-11-03T12:49:13,053][DEBUG][logstash.instrument.periodicpoller.persistentqueue] PeriodicPoller: Starting {:polling_interval=>5, :polling_timeout=>120}
[2017-11-03T12:49:13,056][DEBUG][logstash.instrument.periodicpoller.deadletterqueue] PeriodicPoller: Starting {:polling_interval=>5, :polling_timeout=>120}
[2017-11-03T12:49:13,070][DEBUG][logstash.agent           ] Reading config file {:config_file=>"C:/ELK/logstash-5.6.3/bin/logstash-wad.conf"}
[2017-11-03T12:49:15,477][DEBUG][logstash.inputs.azurewadtable] azurewadtable plugin is using the 'milestone' method to declare the version of the plugin this method is deprecated in favor of declaring the version inside the gemspec.
[2017-11-03T12:49:15,481][DEBUG][logstash.plugins.registry] On demand adding plugin to the registry {:name=>"azurewadtable", :type=>"input", :class=>LogStash::Inputs::AzureWADTable}
[2017-11-03T12:49:15,487][INFO ][logstash.inputs.azurewadtable] Using version 0.9.x input plugin 'azurewadtable'. This plugin should work but would benefit from use by folks like you. Please let us know if you find bugs or have suggestio
ns on how to improve this plugin.
[2017-11-03T12:49:15,527][DEBUG][logstash.plugins.registry] On demand adding plugin to the registry {:name=>"plain", :type=>"codec", :class=>LogStash::Codecs::Plain}
[2017-11-03T12:49:15,535][DEBUG][logstash.codecs.plain    ] config LogStash::Codecs::Plain/@id = "plain_d387f24b-d01f-48c1-9a8b-779b39873f11"
[2017-11-03T12:49:15,535][DEBUG][logstash.codecs.plain    ] config LogStash::Codecs::Plain/@enable_metric = true
[2017-11-03T12:49:15,536][DEBUG][logstash.codecs.plain    ] config LogStash::Codecs::Plain/@charset = "UTF-8"
[2017-11-03T12:49:15,540][DEBUG][logstash.inputs.azurewadtable] config LogStash::Inputs::AzureWADTable/@account_name = "elfiprod"
[2017-11-03T12:49:15,540][DEBUG][logstash.inputs.azurewadtable] config LogStash::Inputs::AzureWADTable/@access_key = "AIOwbezwyK3pckg72udZ2Mup4B2JaLCeaz7OHQkH6hNG/322pHmUcfoJ+ORHFpMqT7Ag1whlfWujpUolIs07oQ=="
[2017-11-03T12:49:15,542][DEBUG][logstash.inputs.azurewadtable] config LogStash::Inputs::AzureWADTable/@table_name = "WADLogsTable"
[2017-11-03T12:49:15,545][DEBUG][logstash.inputs.azurewadtable] config LogStash::Inputs::AzureWADTable/@collection_start_time_utc = "2017-10-23T06:0:00.001Z"
[2017-11-03T12:49:15,545][DEBUG][logstash.inputs.azurewadtable] config LogStash::Inputs::AzureWADTable/@id = "dfc6ef6d6dac08485f1e0b0ef800833db3edb9e0-1"
[2017-11-03T12:49:15,546][DEBUG][logstash.inputs.azurewadtable] config LogStash::Inputs::AzureWADTable/@enable_metric = true
[2017-11-03T12:49:15,547][DEBUG][logstash.inputs.azurewadtable] config LogStash::Inputs::AzureWADTable/@codec = <LogStash::Codecs::Plain id=>"plain_d387f24b-d01f-48c1-9a8b-779b39873f11", enable_metric=>true, charset=>"UTF-8">
[2017-11-03T12:49:15,549][DEBUG][logstash.inputs.azurewadtable] config LogStash::Inputs::AzureWADTable/@add_field = {}
[2017-11-03T12:49:15,552][DEBUG][logstash.inputs.azurewadtable] config LogStash::Inputs::AzureWADTable/@entity_count_to_process = 100
[2017-11-03T12:49:15,554][DEBUG][logstash.inputs.azurewadtable] config LogStash::Inputs::AzureWADTable/@etw_pretty_print = false
[2017-11-03T12:49:15,556][DEBUG][logstash.inputs.azurewadtable] config LogStash::Inputs::AzureWADTable/@idle_delay_seconds = 15
[2017-11-03T12:49:15,557][DEBUG][logstash.inputs.azurewadtable] config LogStash::Inputs::AzureWADTable/@endpoint = "core.windows.net"
[2017-11-03T12:49:15,558][DEBUG][logstash.inputs.azurewadtable] config LogStash::Inputs::AzureWADTable/@data_latency_minutes = 1
[2017-11-03T12:49:15,559][DEBUG][logstash.inputs.azurewadtable] config LogStash::Inputs::AzureWADTable/@past_queries_count = 5
[2017-11-03T12:49:15,575][DEBUG][logstash.plugins.registry] On demand adding plugin to the registry {:name=>"drop", :type=>"filter", :class=>LogStash::Filters::Drop}
[2017-11-03T12:49:15,581][DEBUG][logstash.filters.drop    ] config LogStash::Filters::Drop/@id = "dfc6ef6d6dac08485f1e0b0ef800833db3edb9e0-2"
[2017-11-03T12:49:15,583][DEBUG][logstash.filters.drop    ] config LogStash::Filters::Drop/@enable_metric = true
[2017-11-03T12:49:15,583][DEBUG][logstash.filters.drop    ] config LogStash::Filters::Drop/@add_tag = []
[2017-11-03T12:49:15,584][DEBUG][logstash.filters.drop    ] config LogStash::Filters::Drop/@remove_tag = []
[2017-11-03T12:49:15,586][DEBUG][logstash.filters.drop    ] config LogStash::Filters::Drop/@add_field = {}
[2017-11-03T12:49:15,590][DEBUG][logstash.filters.drop    ] config LogStash::Filters::Drop/@remove_field = []
[2017-11-03T12:49:15,592][DEBUG][logstash.filters.drop    ] config LogStash::Filters::Drop/@periodic_flush = false
[2017-11-03T12:49:15,593][DEBUG][logstash.filters.drop    ] config LogStash::Filters::Drop/@percentage = 100
[2017-11-03T12:49:15,879][DEBUG][logstash.plugins.registry] On demand adding plugin to the registry {:name=>"elasticsearch", :type=>"output", :class=>LogStash::Outputs::ElasticSearch}
[2017-11-03T12:49:15,890][DEBUG][logstash.codecs.plain    ] config LogStash::Codecs::Plain/@id = "plain_276b60d8-de52-4c4b-bd85-4fa67ddabbfe"
[2017-11-03T12:49:15,890][DEBUG][logstash.codecs.plain    ] config LogStash::Codecs::Plain/@enable_metric = true
[2017-11-03T12:49:15,891][DEBUG][logstash.codecs.plain    ] config LogStash::Codecs::Plain/@charset = "UTF-8"
[2017-11-03T12:49:15,897][DEBUG][logstash.outputs.elasticsearch] config LogStash::Outputs::ElasticSearch/@index = "wad"
[2017-11-03T12:49:15,900][DEBUG][logstash.outputs.elasticsearch] config LogStash::Outputs::ElasticSearch/@action = "index"
[2017-11-03T12:49:15,902][DEBUG][logstash.outputs.elasticsearch] config LogStash::Outputs::ElasticSearch/@hosts = [//localhost:9200]
[2017-11-03T12:49:15,906][DEBUG][logstash.outputs.elasticsearch] config LogStash::Outputs::ElasticSearch/@id = "dfc6ef6d6dac08485f1e0b0ef800833db3edb9e0-3"
[2017-11-03T12:49:15,909][DEBUG][logstash.outputs.elasticsearch] config LogStash::Outputs::ElasticSearch/@enable_metric = true
[2017-11-03T12:49:15,910][DEBUG][logstash.outputs.elasticsearch] config LogStash::Outputs::ElasticSearch/@codec = <LogStash::Codecs::Plain id=>"plain_276b60d8-de52-4c4b-bd85-4fa67ddabbfe", enable_metric=>true, charset=>"UTF-8">
[2017-11-03T12:49:15,910][DEBUG][logstash.outputs.elasticsearch] config LogStash::Outputs::ElasticSearch/@workers = 1
[2017-11-03T12:49:15,912][DEBUG][logstash.outputs.elasticsearch] config LogStash::Outputs::ElasticSearch/@manage_template = true
[2017-11-03T12:49:15,918][DEBUG][logstash.outputs.elasticsearch] config LogStash::Outputs::ElasticSearch/@template_name = "logstash"
[2017-11-03T12:49:15,921][DEBUG][logstash.outputs.elasticsearch] config LogStash::Outputs::ElasticSearch/@template_overwrite = false
[2017-11-03T12:49:15,921][DEBUG][logstash.outputs.elasticsearch] config LogStash::Outputs::ElasticSearch/@parent = nil
[2017-11-03T12:49:15,924][DEBUG][logstash.outputs.elasticsearch] config LogStash::Outputs::ElasticSearch/@idle_flush_time = 1
[2017-11-03T12:49:15,928][DEBUG][logstash.outputs.elasticsearch] config LogStash::Outputs::ElasticSearch/@upsert = ""
[2017-11-03T12:49:15,928][DEBUG][logstash.outputs.elasticsearch] config LogStash::Outputs::ElasticSearch/@doc_as_upsert = false
[2017-11-03T12:49:15,929][DEBUG][logstash.outputs.elasticsearch] config LogStash::Outputs::ElasticSearch/@script = ""
[2017-11-03T12:49:15,931][DEBUG][logstash.outputs.elasticsearch] config LogStash::Outputs::ElasticSearch/@script_type = "inline"
[2017-11-03T12:49:15,933][DEBUG][logstash.outputs.elasticsearch] config LogStash::Outputs::ElasticSearch/@script_lang = "painless"
[2017-11-03T12:49:15,937][DEBUG][logstash.outputs.elasticsearch] config LogStash::Outputs::ElasticSearch/@script_var_name = "event"
[2017-11-03T12:49:15,940][DEBUG][logstash.outputs.elasticsearch] config LogStash::Outputs::ElasticSearch/@scripted_upsert = false
[2017-11-03T12:49:15,941][DEBUG][logstash.outputs.elasticsearch] config LogStash::Outputs::ElasticSearch/@retry_initial_interval = 2
[2017-11-03T12:49:15,942][DEBUG][logstash.outputs.elasticsearch] config LogStash::Outputs::ElasticSearch/@retry_max_interval = 64
[2017-11-03T12:49:15,943][DEBUG][logstash.outputs.elasticsearch] config LogStash::Outputs::ElasticSearch/@retry_on_conflict = 1
[2017-11-03T12:49:15,944][DEBUG][logstash.outputs.elasticsearch] config LogStash::Outputs::ElasticSearch/@pipeline = nil
[2017-11-03T12:49:15,946][DEBUG][logstash.outputs.elasticsearch] config LogStash::Outputs::ElasticSearch/@ssl_certificate_verification = true
[2017-11-03T12:49:15,952][DEBUG][logstash.outputs.elasticsearch] config LogStash::Outputs::ElasticSearch/@sniffing = false
[2017-11-03T12:49:15,953][DEBUG][logstash.outputs.elasticsearch] config LogStash::Outputs::ElasticSearch/@sniffing_delay = 5
[2017-11-03T12:49:15,954][DEBUG][logstash.outputs.elasticsearch] config LogStash::Outputs::ElasticSearch/@timeout = 60
[2017-11-03T12:49:15,955][DEBUG][logstash.outputs.elasticsearch] config LogStash::Outputs::ElasticSearch/@failure_type_logging_whitelist = []
[2017-11-03T12:49:15,956][DEBUG][logstash.outputs.elasticsearch] config LogStash::Outputs::ElasticSearch/@pool_max = 1000
[2017-11-03T12:49:15,959][DEBUG][logstash.outputs.elasticsearch] config LogStash::Outputs::ElasticSearch/@pool_max_per_route = 100
[2017-11-03T12:49:15,962][DEBUG][logstash.outputs.elasticsearch] config LogStash::Outputs::ElasticSearch/@resurrect_delay = 5
[2017-11-03T12:49:15,964][DEBUG][logstash.outputs.elasticsearch] config LogStash::Outputs::ElasticSearch/@validate_after_inactivity = 10000
[2017-11-03T12:49:15,967][DEBUG][logstash.outputs.elasticsearch] config LogStash::Outputs::ElasticSearch/@http_compression = false
[2017-11-03T12:49:15,988][DEBUG][logstash.agent           ] starting agent
[2017-11-03T12:49:15,997][DEBUG][logstash.agent           ] starting pipeline {:id=>"main"}
[2017-11-03T12:49:16,004][DEBUG][logstash.outputs.elasticsearch] Normalizing http path {:path=>nil, :normalized=>nil}
[2017-11-03T12:49:16,334][INFO ][logstash.outputs.elasticsearch] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://localhost:9200/]}}
[2017-11-03T12:49:16,339][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://localhost:9200/, :path=>"/"}
[2017-11-03T12:49:16,466][WARN ][logstash.outputs.elasticsearch] Restored connection to ES instance {:url=>"http://localhost:9200/"}
[2017-11-03T12:49:16,524][INFO ][logstash.outputs.elasticsearch] Using mapping template from {:path=>nil}
[2017-11-03T12:49:16,531][INFO ][logstash.outputs.elasticsearch] Attempting to install template {:manage_template=>{"template"=>"logstash-*", "version"=>50001, "settings"=>{"index.refresh_interval"=>"5s"}, "mappings"=>{"_default_"=>{"_al
l"=>{"enabled"=>true, "norms"=>false}, "dynamic_templates"=>[{"message_field"=>{"path_match"=>"message", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false}}}, {"string_fields"=>{"match"=>"*", "match_mapping_type"
=>"string", "mapping"=>{"type"=>"text", "norms"=>false, "fields"=>{"keyword"=>{"type"=>"keyword", "ignore_above"=>256}}}}}], "properties"=>{"@timestamp"=>{"type"=>"date", "include_in_all"=>false}, "@version"=>{"type"=>"keyword", "include
_in_all"=>false}, "geoip"=>{"dynamic"=>true, "properties"=>{"ip"=>{"type"=>"ip"}, "location"=>{"type"=>"geo_point"}, "latitude"=>{"type"=>"half_float"}, "longitude"=>{"type"=>"half_float"}}}}}}}}
[2017-11-03T12:49:16,543][DEBUG][logstash.outputs.elasticsearch] Found existing Elasticsearch template. Skipping template management {:name=>"logstash"}
[2017-11-03T12:49:16,546][INFO ][logstash.outputs.elasticsearch] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["//localhost:9200"]}
[2017-11-03T12:49:16,555][INFO ][logstash.pipeline        ] Starting pipeline {"id"=>"main", "pipeline.workers"=>4, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>500}
[2017-11-03T12:49:16,570][ERROR][logstash.pipeline        ] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {"exception"=>"undefined method `to_hash' f
or []:Array", "backtrace"=>["(eval):41:in `filter_func'", "C:/ELK/logstash-5.6.3/logstash-core/lib/logstash/pipeline.rb:398:in `filter_batch'", "C:/ELK/logstash-5.6.3/logstash-core/lib/logstash/pipeline.rb:379:in `worker_loop'", "C:/ELK/
logstash-5.6.3/logstash-core/lib/logstash/pipeline.rb:342:in `start_workers'"]}
[2017-11-03T12:49:16,598][ERROR][logstash.pipeline        ] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {"exception"=>"undefined method `to_hash' f
or []:Array", "backtrace"=>["(eval):41:in `filter_func'", "C:/ELK/logstash-5.6.3/logstash-core/lib/logstash/pipeline.rb:398:in `filter_batch'", "C:/ELK/logstash-5.6.3/logstash-core/lib/logstash/pipeline.rb:379:in `worker_loop'", "C:/ELK/
logstash-5.6.3/logstash-core/lib/logstash/pipeline.rb:342:in `start_workers'"]}
[2017-11-03T12:49:16,614][ERROR][logstash.pipeline        ] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {"exception"=>"undefined method `to_hash' f
or []:Array", "backtrace"=>["(eval):41:in `filter_func'", "C:/ELK/logstash-5.6.3/logstash-core/lib/logstash/pipeline.rb:398:in `filter_batch'", "C:/ELK/logstash-5.6.3/logstash-core/lib/logstash/pipeline.rb:379:in `worker_loop'", "C:/ELK/
logstash-5.6.3/logstash-core/lib/logstash/pipeline.rb:342:in `start_workers'"]}
NoMethodError: undefined method `to_hash' for []:Array
    filter_func at (eval):41
   filter_batch at C:/ELK/logstash-5.6.3/logstash-core/lib/logstash/pipeline.rb:398
    worker_loop at C:/ELK/logstash-5.6.3/logstash-core/lib/logstash/pipeline.rb:379
  start_workers at C:/ELK/logstash-5.6.3/logstash-core/lib/logstash/pipeline.rb:342
[2017-11-03T12:49:16,631][ERROR][logstash.pipeline        ] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {"exception"=>"undefined method `to_hash' f
or []:Array", "backtrace"=>["(eval):41:in `filter_func'", "C:/ELK/logstash-5.6.3/logstash-core/lib/logstash/pipeline.rb:398:in `filter_batch'", "C:/ELK/logstash-5.6.3/logstash-core/lib/logstash/pipeline.rb:379:in `worker_loop'", "C:/ELK/
logstash-5.6.3/logstash-core/lib/logstash/pipeline.rb:342:in `start_workers'"]}
PS C:\ELK\logstash-5.6.3\bin>`

**Comment by clguimanMSFT** [comment]
@Joffinn you accidentally leaked your storage key, you should reset it :)
The logs provided only show the initialization part of the plugin, there are no logs with the actual query running. You should see something like "Query filter: "
