### ISSUE TITLE
Oh My, An error occurred. undefined method `type' for #<NoMethodError:0x79fbf8f9>:

### ISSUE THREAD

**Issue by pwalters04** [Azure/azure-diagnostics-tools#157]
Please confirm if the file in the container needs to be JSON.

**Comment by brahmnes** [comment]
Hi @pwalters04 

I assume you are referring to the azureblob input plugin. No, the file doesn't need to be json. Do you have a callstack showing where the exception was thrown?

The only place I see it references type is this line
https://github.com/Azure/azure-diagnostics-tools/blob/master/Logstash/logstash-input-azureblob/lib/logstash/inputs/azureblob.rb#L305

But it checks for the existence of it before it accesses it.

**Comment by pwalters04** [comment]
Hi @brahmnes , 

I am still receiving the same error.  Below is my config file:
`input
{
    azureblob
    {
        storage_account_name => "accountname"
        storage_access_key => "******************"
        container => "logs"
        codec => multiline {
            pattern => "^\t\t\{\r"
            negate => true
            what =>  previous
            max_lines => 50000
        }
    }
}
filter {
 mutate {
        gsub => [ "message","]","" ]
        gsub => [ "message","\t","" ]
        gsub => [ "message","\r","" ]
        gsub => [ "message","\n","" ]
        gsub => [ "message","},","}" ]
   }
   json  { source => "message"  }
   mutate { remove_field => ["message"] }
}
output {
  elasticsearch { 
                hosts => ["elasticsearchdev-vm-0:9200"]
                index=>"blob_logs"
                user => *****
                password => ****** }
  stdout { codec => rubydebug }
}`

`[2018-07-20T14:00:19,718][ERROR][logstash.pipeline        ] Error registering plugin {:pipeline_id=>"main", :plugin=>"<LogStash::Inputs::LogstashInputAzureblob storage_account_name=>\"************\", storage_access_key=>\"*******", container=>\"logs\", codec=><LogStash::Codecs::Multiline pattern=>\"^\\\\t\\\\t\\\\{\\\\r\", negate=>true, what=>\"previous\", max_lines=>50000, id=>\"43e33868-6c23-49cc-b128-301f52373b13\", enable_metric=>true, charset=>\"UTF-8\", multiline_tag=>\"multiline\", max_bytes=>10485760>, id=>\"89f562fdcc6f56004143518d4d1d1999cf112a5be697ec50686bcab66593d860\", enable_metric=>true, endpoint=>\"core.windows.net\", registry_path=>\"data/registry\", registry_lease_duration=>15, interval=>30, registry_create_policy=>\"resume\", file_head_bytes=>0, file_tail_bytes=>0, blob_list_page_size=>100, file_chunk_size_bytes=>4194304>", :error=>"No route to host", :thread=>"#<Thread:0x50136d33 run>"}
[2018-07-20T14:00:20,172][ERROR][logstash.pipeline        ] Pipeline aborted due to error {:pipeline_id=>"main", :exception=>#<IOError: No route to host>, :backtrace=>["org/jruby/ext/socket/RubyUDPSocket.java:441:in `send'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/resolv.rb:803:in `send'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/resolv.rb:680:in `request'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/resolv.rb:536:in `block in fetch_resource'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/resolv.rb:1108:in `block in resolv'", "org/jruby/RubyArray.java:1734:in `each'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/resolv.rb:1106:in `block in resolv'", "org/jruby/RubyArray.java:1734:in `each'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/resolv.rb:1105:in `block in resolv'", "org/jruby/RubyArray.java:1734:in `each'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/resolv.rb:1103:in `resolv'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/resolv.rb:527:in `fetch_resource'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/resolv.rb:517:in `each_resource'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/resolv.rb:498:in `getresource'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/remote_fetcher.rb:105:in `api_endpoint'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/source.rb:47:in `api_uri'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/source.rb:187:in `load_specs'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/spec_fetcher.rb:267:in `tuples_for'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/spec_fetcher.rb:231:in `block in available_specs'", "org/jruby/RubyArray.java:1734:in `each'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/source_list.rb:98:in `each_source'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/spec_fetcher.rb:227:in `available_specs'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/spec_fetcher.rb:103:in `search_for_dependency'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/spec_fetcher.rb:167:in `spec_for_dependency'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems.rb:949:in `latest_spec_for'", "/Users/h246632/Logstash/logstash-6.3.0/vendor/bundle/jruby/2.3.0/gems/logstash-input-azureblob-0.9.12-java/lib/logstash/inputs/azureblob.rb:124:in `register'", "/Users/h246632/Logstash/logstash-6.3.0/logstash-core/lib/logstash/pipeline.rb:340:in `register_plugin'", "/Users/h246632/Logstash/logstash-6.3.0/logstash-core/lib/logstash/pipeline.rb:351:in `block in register_plugins'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/h246632/Logstash/logstash-6.3.0/logstash-core/lib/logstash/pipeline.rb:351:in `register_plugins'", "/Users/h246632/Logstash/logstash-6.3.0/logstash-core/lib/logstash/pipeline.rb:498:in `start_inputs'", "/Users/h246632/Logstash/logstash-6.3.0/logstash-core/lib/logstash/pipeline.rb:392:in `start_workers'", "/Users/h246632/Logstash/logstash-6.3.0/logstash-core/lib/logstash/pipeline.rb:288:in `run'", "/Users/h246632/Logstash/logstash-6.3.0/logstash-core/lib/logstash/pipeline.rb:248:in `block in start'"], :thread=>"#<Thread:0x50136d33 run>"}
[2018-07-20T14:00:20,201][ERROR][logstash.agent           ] Failed to execute action {:id=>:main, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Could not execute action: PipelineAction::Create<main>, action_result: false", :backtrace=>nil}
[2018-07-20T14:00:20,615][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2018-07-20T14:00:25,739][ERROR][logstash.inputs.logstashinputazureblob] Oh My, An error occurred. undefined method `type' for #<NoMethodError:0x50d68ad9>:
["/Users/h246632/Logstash/logstash-6.3.0/vendor/bundle/jruby/2.3.0/gems/logstash-input-azureblob-0.9.12-java/lib/logstash/inputs/azureblob.rb:309:in `acquire_lease'", "/Users/h246632/Logstash/logstash-6.3.0/vendor/bundle/jruby/2.3.0/gems/logstash-input-azureblob-0.9.12-java/lib/logstash/inputs/azureblob.rb:417:in `cleanup_registry'", "/Users/h246632/Logstash/logstash-6.3.0/vendor/bundle/jruby/2.3.0/gems/logstash-input-azureblob-0.9.12-java/lib/logstash/inputs/azureblob.rb:148:in `stop'", "/Users/h246632/Logstash/logstash-6.3.0/logstash-core/lib/logstash/inputs/base.rb:89:in `do_stop'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/h246632/Logstash/logstash-6.3.0/logstash-core/lib/logstash/pipeline.rb:567:in `stop_inputs'", "/Users/h246632/Logstash/logstash-6.3.0/logstash-core/lib/logstash/pipeline.rb:550:in `shutdown'", "/Users/h246632/Logstash/logstash-6.3.0/logstash-core/lib/logstash/pipeline_action/stop.rb:16:in `block in execute'", "/Users/h246632/Logstash/logstash-6.3.0/logstash-core/lib/logstash/pipeline_action/stop.rb:15:in `execute'", "/Users/h246632/Logstash/logstash-6.3.0/logstash-core/lib/logstash/agent.rb:305:in `block in converge_state'"] {:exception=>#<NoMethodError: undefined method `type' for #<NoMethodError:0x50d68ad9>>}`

**Comment by brahmnes** [comment]
Hi @pwalters04,

Sorry for the delayed response. I did some research and found that object.type has been deprecated in ruby a while ago. The new replacement is object.class. That's why the NoMethodError comes up.

To fix this problem, you can edit the source directly. Around line azureblob.rb;309, you an change this line

if(e.type && e.type == 'LeaseAlreadyPresent')

to something like 

if (e.class.name.include? 'LeaseAlreadyPresent')

And see if that works for you? If it does, feel free to submit a PR.

**Comment by brahmnes** [comment]
Hi @pwalters04,

This fix has been checked in and version 0.9.13 has been released with the fix. Let me know if this doesn't work for you.
