### ISSUE TITLE
no implicit conversion of nil into String for com/microsoft/json-parser.rb:3

### ISSUE THREAD

**Issue by zgqallen** [Azure/azure-diagnostics-tools#170]
When i install latest plug with version 0.9.13 in logstash-6.0.1, after install the plugin and start the logstash and get a logstash plugin loading error:
[2018-09-19T09:15:49,181][ERROR][logstash.plugins.registry] Problems loading a plugin with {:type=>"input", :name=>"azureblob", :path=>"logstash/inputs/azureblob", :error_message=>"no implicit conversion of nil into String", :error_class=>TypeError, :error_backtrace=>["org/jruby/RubyKernel.java:957:in `require'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-azureblob-0.9.13/lib/com/microsoft/json-parser.rb:3:in `<main>'", "org/jruby/RubyKernel.java:955:in `...

Check the file com/microsoft/json-parser.rb:3
require Dir[ File.dirname(__FILE__) + "/../../*_jars.rb" ].first

Found there seems really no ../../*_jars.rb in the lib dir. Does the new plugin miss some file or we need install this file from some place? Thanks!

**Comment by erikpaperik** [comment]
I'm currently having the same issue.

**Comment by brahmnes** [comment]
In the lib folder, there should be a logstash-input-azureblob_jars.rb file.
Did you install it using logstash-plugin?

**Comment by yardbirdsax** [comment]
I'm having the same issue. I did install it using logstash-plugin just as it lists in the README file.

**Comment by yardbirdsax** [comment]
Just to see if a fresh install helped, I downloaded the latest logstash build and followed these steps.

PS C:\elk\Logstash-642> .\bin\logstash-plugin install logstash-input-azureblob
Validating logstash-input-azureblob
Installing logstash-input-azureblob

Here are all the contents of the directory:

PS C:\elk\Logstash-642> dir .\vendor\bundle\jruby\2.3.0\gems\logstash-input-azureblob-0.9.13-java\ -Recurse | select FullName

FullName
--------
C:\elk\Logstash-642\vendor\bundle\jruby\2.3.0\gems\logstash-input-azureblob-0.9.13-java\lib
C:\elk\Logstash-642\vendor\bundle\jruby\2.3.0\gems\logstash-input-azureblob-0.9.13-java\spec
C:\elk\Logstash-642\vendor\bundle\jruby\2.3.0\gems\logstash-input-azureblob-0.9.13-java\CHANGELOG.md
C:\elk\Logstash-642\vendor\bundle\jruby\2.3.0\gems\logstash-input-azureblob-0.9.13-java\Gemfile
C:\elk\Logstash-642\vendor\bundle\jruby\2.3.0\gems\logstash-input-azureblob-0.9.13-java\LICENSE
C:\elk\Logstash-642\vendor\bundle\jruby\2.3.0\gems\logstash-input-azureblob-0.9.13-java\logstash-input-azureblob.gemspec
C:\elk\Logstash-642\vendor\bundle\jruby\2.3.0\gems\logstash-input-azureblob-0.9.13-java\README.md
C:\elk\Logstash-642\vendor\bundle\jruby\2.3.0\gems\logstash-input-azureblob-0.9.13-java\lib\com
C:\elk\Logstash-642\vendor\bundle\jruby\2.3.0\gems\logstash-input-azureblob-0.9.13-java\lib\logstash
C:\elk\Logstash-642\vendor\bundle\jruby\2.3.0\gems\logstash-input-azureblob-0.9.13-java\lib\com\microsoft
C:\elk\Logstash-642\vendor\bundle\jruby\2.3.0\gems\logstash-input-azureblob-0.9.13-java\lib\com\microsoft\json-parser.rb
C:\elk\Logstash-642\vendor\bundle\jruby\2.3.0\gems\logstash-input-azureblob-0.9.13-java\lib\logstash\inputs
C:\elk\Logstash-642\vendor\bundle\jruby\2.3.0\gems\logstash-input-azureblob-0.9.13-java\lib\logstash\inputs\azureblob.rb
C:\elk\Logstash-642\vendor\bundle\jruby\2.3.0\gems\logstash-input-azureblob-0.9.13-java\spec\com
C:\elk\Logstash-642\vendor\bundle\jruby\2.3.0\gems\logstash-input-azureblob-0.9.13-java\spec\inputs
C:\elk\Logstash-642\vendor\bundle\jruby\2.3.0\gems\logstash-input-azureblob-0.9.13-java\spec\com\microsoft
C:\elk\Logstash-642\vendor\bundle\jruby\2.3.0\gems\logstash-input-azureblob-0.9.13-java\spec\com\microsoft\json-parser_spec.rb
C:\elk\Logstash-642\vendor\bundle\jruby\2.3.0\gems\logstash-input-azureblob-0.9.13-java\spec\inputs\azureblob_spec.rb

So it seems to be missing a bunch of the files you have listed above. I'll try on a Linux box and see if I get the same result.

**Comment by yardbirdsax** [comment]
So on a clean CentOS install with Logstash 6.4.1 it works fine! This also resolves my issue from #176. Maybe a Windows related issue then?

**Comment by MrJerB** [comment]
Experiencing the same on a Windows-based docker container.

**Comment by beyond-code-github** [comment]
I am also experiencing this, trying to install the plugin within the docker container provided by https://elk-docker.readthedocs.io/

I too am missing the *.rb files I'd expect to see in the lib dir:

``` 
root@5ac29cf645b6:/opt/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-azureblob-0.9.13-java/lib# ls
com  logstash
```

**Comment by brahmnes** [comment]
Hi @beyond-code-github 

Thanks for the info. I am not sure about the image at https://elk-docker.readthedocs.io, I would recommend getting the official image from elastic
https://www.elastic.co/guide/en/logstash/current/docker.html

The official image is docker.elastic.co/logstash/logstash, and this works for me.
I wonder if it's the ruby version that makes a difference. If you can share the version of ruby where it didn't work for you, I can compare, and maybe it would give some hints.

I still haven't tried it on Windows yet, will do that when I have time and see where the difference could be.

**Comment by MrJerB** [comment]
Just tried inside docker container using image openjdk:8-windowsservercore-ltsc2016. 
I downloaded logstash from https://artifacts.elastic.co/downloads/logstash/logstash-6.4.3.zip

I still have files missing:

```
PS C:\logstash\vendor\bundle\jruby\2.3.0\gems\logstash-input-azureblob-0.9.13-java\lib> ls


    Directory: C:\logstash\vendor\bundle\jruby\2.3.0\gems\logstash-input-azureblob-0.9.13-java\lib


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       11/14/2018  10:06 AM                com
d-----       11/14/2018  10:06 AM                logstash
```

Going to try the same process from a Windows 10 workstation outside Docker.

**Comment by jawiz** [comment]
Bump! Still experiencing this issue on windows machines. Any ideas?

**Comment by sunkarakamal** [comment]
Hi Admin , 

The issue is still open , At present we are doing work around copying the files that are required for blob storage " logstash-input-azureblob_jars.rb" and  "org/glassfish/javax.json/1.1/javax.json-1.1.jar".

is there Any permanent fix expected soon or later? 

![image](https://user-images.githubusercontent.com/30232460/82229857-dc2b8980-9922-11ea-9e06-4834e4e37645.png)

**Comment by trigodeepak** [comment]
@sunkarakamal I am still facing the same issue.(Running on windows10 machine). 
Please elaborate the the workaround for this, From where we should fetch these files :  logstash-input-azureblob_jars.rb" and "org/glassfish/javax.json/1.1/javax.json-1.1.jar".

**Comment by trigodeepak** [comment]
@sunkarakamal  I have found the files and workaround 
Here are the steps to follow for the same : 
1. I have downloaded the older gem pakage(v0.9.12) https://rubygems.org/gems/logstash-input-azureblob/versions/0.9.12-java using this url 
2. Unzip the gem package using 7 zip ( then extract data.tar.gz ) (There is a folder named "lib" inside data)
3. here is the SS for lib folder 
![image](https://user-images.githubusercontent.com/26536200/83136469-2a037700-a105-11ea-92ee-a28e52aeddae.png)
4. Paste these 2 inside your plugin installation lib folder (Which is as follows): 
logstash-7.6.2\vendor\bundle\jruby\2.5.0\gems\logstash-input-azureblob-0.9.13-java\lib
5. here are the 2 files in zip format 
[logstash-input-lib.zip](https://github.com/Azure/azure-diagnostics-tools/files/4695236/logstash-input-lib.zip)
You can paste directly in lib folder same as in step 4.

**Comment by hadens** [comment]
@trigodeepak, your suggestion resolved my issue.

I was able to reproduce this on Ubuntu 18.04.
