### ISSUE TITLE
azureblob logstash plugin is not working

### ISSUE THREAD

**Issue by kp2822** [Azure/azure-diagnostics-tools#178]
-I setup logstash azureblob-plugin to fetch data from storage account and send it to elasticsearch cluster
-I can see the pipeline is starting without any issue but it is not able to fetch any data
-Verified all the setting on azure storage account including logs , firewall and i can see it receive requests from azure blob plugin

**Comment by kp2822** [comment]
> Are you trying to ingest existing files, or log files created after you started the logstash plugin?
> 
> You may want to look at the plugin parameter: registry_create_policy
> 
> The plugin does not pull existing data by default, it only polls for new.

Logstash is starting pipeline but it is not fetching any data.
I verify the azure storage account logs and i can see the hits.
Also, I added File Output in the logstash pipeline config file and i can see it is able to save data in that file.
But, It is not able to send data to the elasticsearch cluster using http
It looks like there is a compatibility issue between azureblob plugin and logstash 6.4.2
How can i check registry_create_policy ??

**Comment by cscheib** [comment]
The parameter is documented here: https://github.com/Azure/azure-diagnostics-tools/tree/master/Logstash/logstash-input-azureblob

You'll have to configure the setting, stop logstash, then blow away your registry (data/ in the storage account), then start logstash.  This clears the registry, and should allow logstash to ingest existing/old files.  

If you don't clear the existing registry first, it'll have the file markers from when the plugin was configured to ignore existing files.

**Comment by kp2822** [comment]
> The parameter is documented here: https://github.com/Azure/azure-diagnostics-tools/tree/master/Logstash/logstash-input-azureblob
> 
> You'll have to configure the setting, stop logstash, then blow away your registry (data/ in the storage account), then start logstash. This clears the registry, and should allow logstash to ingest existing/old files.
> 
> If you don't clear the existing registry first, it'll have the file markers from when the plugin was configured to ignore existing files.

One of the pipeline is started working after deleting registry blob.

Thank you @cscheib

**Comment by feedblade** [comment]
Error registering plugin {:pipeline_id=>"main", :plugin=>"<LogStash::Inputs::LogstashInputAzureblob container=>\"insights-logs-applicationxxxxxxxxxxxx\", codec=><LogStash::Codecs::JSON id=>\"json_402cc503-6682-41c7-b9d7-a48ea21ddd3e\", enable_metric=>true, charset=>\"UTF-8\">, id=>\"651918634b0658c67ba09daeb3f934041b80c233049021634e0dd2fc27dd3d44\", storage_account_name=>\"xxxxxxxxxx\", storage_access_key=>\"xxxxxxxxxxxxxxxxxxxxxxxxxxxxx", enable_metric=>true, endpoint=>\"core.windows.net\", registry_path=>\"data/registry\", registry_lease_duration=>15, interval=>30, registry_create_policy=>\"resume\", file_head_bytes=>0, file_tail_bytes=>0, blob_list_page_size=>100, file_chunk_size_bytes=>4194304>", :error=>"options provided are not valid set: {:storage_account_name=>\"xxxxxxx\", :storage_access_key=>\"lxxxxxxxxxxxxxxxxxxxxxxx", :storage_blob_host=>\"xxxxxxxxxxxxxxxxxxxx\"}", :thread=>"#<Thread:0x56e70cdd run>"}



2019-05-31T04:30:19,103][ERROR][logstash.pipeline        ] Pipeline aborted due to error {:pipeline_id=>"main", :exception=>#<Azure::Storage::InvalidOptionsError: options provided are not valid set: {:storage_account_name=>"xxxx", :storage_access_key=>"xxxxxxxxxxxxxxxxx", :storage_blob_host=>"https://xxxxxxxxxxxxxxxx"}>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/azure-storage-0.15.0.preview/lib/azure/storage/client_options.rb:257:in `filter'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/azure-storage-0.15.0.preview/lib/azure/storage/client_options.rb:88:in `reset!'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/azure-storage-0.15.0.preview/lib/azure/storage/client.rb:91:in `initialize'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/azure-storage-0.15.0.preview/lib/azure/storage/client.rb:160:in `create'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-azureblob-0.9.13-java/lib/logstash/inputs/azureblob.rb:141:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:242:in `register_plugin'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:253:in `block in register_plugins'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:253:in `register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:396:in `start_inputs'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:294:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:200:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:160:in `block in start'"], :thread=>"#<Thread:0x56e70cdd run>"}
[2019-05-31T04:30:19,127][ERROR][logstash.agent           ] Failed to execute action {:id=>:main, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Could not execute action: PipelineAction::Create<main>, action_result: false", :backtrace=>nil}

Here is my config 

input {
azureblob
{
storage_account_name => "xxxxxxxxxxxxx"
storage_access_key => "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
container => "insights-logs-applicationgatewayaccesslog"
codec => "json"
 }
}
filter {
date {
match => ["unixtimestamp" , "UNIX"]
 }
}
output {
elasticsearch {
hosts => "localhost:9200"
index => "waf-access-logs"
 }
}

**Comment by L1nja** [comment]
@cscheib I have the similar issue of logstash not ingesting my older azure blob logs. Basically my logstash stopped ingesting 2 days ago and I got that fixed yesterday. However it is only ingesting the current logs and not what was missed.

When you say delete the registry file, Do you mean delete the registry file contained within the Azure blob Storage container? 
If yes, what is the impact on that with the container?

Thanks.

**Comment by amit1411** [comment]
Is this plugin compatible with logstash 7.7.0 ? I am facing the same issue and my registry file is not getting created. I dont see any errors even in debug mode.

**Comment by ottodeng** [comment]
same error from my test with ubuntu18.04 logstash-7.10.2

[main] Pipeline error {:pipeline_id=>"main", :exception=>#<Azure::Storage::InvalidOptionsError: options provided are not valid set: {:storage_account_name=>"xxxxx", :storage_access_key=>"xxxxxxxxxxxxEj6vV3W/7Dw==", :storage_blob_host=>"https://xxx.blob.core.windows.net"}>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/azure-storage-0.15.0.preview/lib/azure/storage/client_options.rb:257:in `filter'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/azure-storage-0.15.0.preview/lib/azure/storage/client_options.rb:88:in `reset!'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/azure-storage-0.15.0.preview/lib/azure/storage/client.rb:91:in `initialize'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/azure-storage-0.15.0.preview/lib/azure/storage/client.rb:160:in `create'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-azureblob-0.9.13-java/lib/logstash/inputs/azureblob.rb:141:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:228:in `block in register_plugins'", "org/jruby/RubyArray.java:1809:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:227:in `register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:386:in `start_inputs'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:311:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:185:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:137:in `block in start'"], "pipeline.sources"=>["/etc/logstash/conf.d/nsg2.conf"], :thread=>"#<Thread:0x4da8380f run>"}


here is my logstash.conf

input {
   azureblob {
         storage_account_name => "xxxxx"
         storage_access_key => "xxxxxxxxxxxxxx/7Dw=="
         container => "insights-logs-networksecuritygroupflowevent"
         codec => "json"
         # Refer https://docs.microsoft.com/azure/network-watcher/network-watcher-read-nsg-flow-logs
         # Typical numbers could be 21/9 or 12/2 depends on the nsg log file types
         #file_head_bytes => 12
         #file_tail_bytes => 2
         # Enable / tweak these settings when event is too big for codec to handle.
         # break_json_down_policy => "with_head_tail"
         # break_json_batch_count => 2
         # registry_create_policy => "start_over"
    }
}


output {
    stdout {  }

}

**Comment by vitthaltambe-gep** [comment]
I am trying to install this plugin in Logstash (8.6) but getting the below error.
The same plugin and pipeline are working with Logstash (7.2).

/usr/share/logstash/bin/logstash-plugin install logstash-input-azureblob

Error:
Installing logstash-input-azureblob
Plugin version conflict, aborting
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "faraday":
  In snapshot (Gemfile.lock):
    faraday (= 1.10.3)

  In Gemfile:
    logstash-input-azureblob was resolved to 0.9.7, which depends on
      azure (~> 0.7.1) was resolved to 0.7.10, which depends on
        faraday (~> 0.9)

    logstash-core was resolved to 8.7.0, which depends on
      elasticsearch (~> 7) was resolved to 7.17.7, which depends on
        elasticsearch-transport (= 7.17.7) was resolved to 7.17.7, which depends on
          faraday (~> 1)

Deleting your Gemfile.lock file and running `bundle install` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
Bundler could not find compatible versions for gem "logstash-input-azureblob":
  In Gemfile:
    logstash-input-azureblob
