### ISSUE TITLE
Unable to load plugin

### ISSUE THREAD

**Issue by nrupaks** [Azure/azure-diagnostics-tools#181]
I have installed the azureblob plugin, and using basic configuration, but getting this error

[2018-12-20T00:08:42,966][ERROR][logstash.plugins.registry] Problems loading a plugin with {:type=>"input", :name=>"azureblob", :path=>"logstash/inputs/azureblob", :error_message=>"no implicit conversion of nil into String", :error_class=>TypeError, :error_backtrace=>["org/jruby/RubyKernel.java:957:in `require'", "C:/logstash-6.5.3/vendor/bundle/jruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'", "C:/logstash-6.5.3/vendor/bundle/jruby/2.3.0/gems/logstash-input-azureblob-0.9.13-java/lib/com/microsoft/json-parser.rb:3:in `<main>'", "org/jruby/RubyKernel.java:955:in `require'", "C:/logstash-6.5.3/vendor/bundle/jruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'", "C:/logstash-6.5.3/vendor/bundle/jruby/2.3.0/gems/logstash-input-azureblob-0.9.13-java/lib/logstash/inputs/azureblob.rb:1:in `<main>'", "org/jruby/RubyKernel.java:955:in `require'", "C:/logstash-6.5.3/vendor/bundle/jruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'", "C:/logstash-6.5.3/logstash-core/lib/logstash/plugins/registry.rb:181:in `legacy_lookup'", "C:/logstash-6.5.3/logstash-core/lib/logstash/plugins/registry.rb:156:in `block in lookup'", "org/jruby/ext/thread/Mutex.java:148:in `synchronize'", "C:/logstash-6.5.3/logstash-core/lib/logstash/plugins/registry.rb:152:in `lookup'", "C:/logstash-6.5.3/logstash-core/lib/logstash/plugins/registry.rb:206:in `lookup_pipeline_plugin'", "C:/logstash-6.5.3/logstash-core/lib/logstash/plugin.rb:137:in `lookup'", "org/logstash/plugins/PluginFactoryExt.java:210:in `plugin'", "org/logstash/plugins/PluginFactoryExt.java:166:in `plugin'", "C:/logstash-6.5.3/logstash-core/lib/logstash/pipeline.rb:71:in `plugin'", "C:/logstash-6.5.3/vendor/bundle/jruby/2.3.0/gems/logstash-input-azureblob-0.9.13-java/lib/logstash/inputs/azureblob.rb:10:in `<eval>'", "org/jruby/RubyKernel.java:994:in `eval'", "C:/logstash-6.5.3/logstash-core/lib/logstash/pipeline.rb:49:in `initialize'", "C:/logstash-6.5.3/logstash-core/lib/logstash/pipeline.rb:90:in `initialize'", "C:/logstash-6.5.3/logstash-core/lib/logstash/pipeline_action/create.rb:42:in `block in execute'", "C:/logstash-6.5.3/logstash-core/lib/logstash/agent.rb:92:in `block in exclusive'", "org/jruby/ext/thread/Mutex.java:148:in `synchronize'", "C:/logstash-6.5.3/logstash-core/lib/logstash/agent.rb:92:in `exclusive'", "C:/logstash-6.5.3/logstash-core/lib/logstash/pipeline_action/create.rb:38:in `execute'", "C:/logstash-6.5.3/logstash-core/lib/logstash/agent.rb:317:in `block in converge_state'"]}
[2018-12-20T00:08:43,021][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"LogStash::PluginLoadingError", :message=>"Couldn't find any input plugin named 'azureblob'. Are you sure this is correct? Trying to load the azureblob input plugin resulted in this error: Problems loading the requested plugin named azureblob of type input. Error: TypeError no implicit conversion of nil into String", :backtrace=>["C:/logstash-6.5.3/logstash-core/lib/logstash/plugins/registry.rb:211:in `lookup_pipeline_plugin'", "C:/logstash-6.5.3/logstash-core/lib/logstash/plugin.rb:137:in `lookup'", "org/logstash/plugins/PluginFactoryExt.java:210:in `plugin'", "org/logstash/plugins/PluginFactoryExt.java:166:in `plugin'", "C:/logstash-6.5.3/logstash-core/lib/logstash/pipeline.rb:71:in `plugin'", "(eval):8:in `<eval>'", "org/jruby/RubyKernel.java:994:in `eval'", "C:/logstash-6.5.3/logstash-core/lib/logstash/pipeline.rb:49:in `initialize'", "C:/logstash-6.5.3/logstash-core/lib/logstash/pipeline.rb:90:in `initialize'", "C:/logstash-6.5.3/logstash-core/lib/logstash/pipeline_action/create.rb:42:in `block in execute'", "C:/logstash-6.5.3/logstash-core/lib/logstash/agent.rb:92:in `block in exclusive'", "org/jruby/ext/thread/Mutex.java:148:in `synchronize'", "C:/logstash-6.5.3/logstash-core/lib/logstash/agent.rb:92:in `exclusive'", "C:/logstash-6.5.3/logstash-core/lib/logstash/pipeline_action/create.rb:38:in `execute'", "C:/logstash-6.5.3/logstash-core/lib/logstash/agent.rb:317:in `block in converge_state'"]}
[2018-12-20T00:08:43,819][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}

**Comment by MrJerB** [comment]
Seems like a duplicate of #170

**Comment by nrupaks** [comment]
looks similar but I have also installed the plugin using logstash-plugin command. My version is 6.5.3 and is running on windows. Should I be doing something else as well?
