### ISSUE TITLE
logstash-input-azureblob (0.9.13) lease issues with data/registry

### ISSUE THREAD

**Issue by GenCr** [Azure/azure-diagnostics-tools#182]
Hi all,

I'm using logstash-input-azureblob (0.9.13) to process NSG Flow Logs from our Azure environment. Initially when I set it up, there were no issues and logs were being processed fine. However, at some point data stopped being processed. Logstash has the following errors in the log file which indicate that the issue is lease related:
'''
[2018-12-20T11:24:22,648][ERROR][logstash.inputs.logstashinputazureblob] Oh My, An error occurred. LeaseLost (412): A lease ID was specified, but the lease for the blob has expired.
RequestId:c3034529-001e-002c-0656-98c448000000
Time:2018-12-20T11:24:10.5736280Z: ["/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/azure-core-0.1.15/lib/azure/core/http/retry_policy.rb:58:in `call'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/azure-core-0.1.15/lib/azure/core/http/http_request.rb:110:in `block in with_filter'", "org/jruby/RubyMethod.java:111:in `call'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/azure-core-0.1.15/lib/azure/core/http/signer_filter.rb:28:in `call'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/azure-core-0.1.15/lib/azure/core/http/http_request.rb:110:in `block in with_filter'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/azure-core-0.1.15/lib/azure/core/service.rb:36:in `call'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/azure-core-0.1.15/lib/azure/core/filtered_service.rb:34:in `call'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/azure-core-0.1.15/lib/azure/core/signed_service.rb:41:in `call'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/azure-storage-0.15.0.preview/lib/azure/storage/service/storage_service.rb:62:in `call'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/azure-storage-0.15.0.preview/lib/azure/storage/blob/blob_service.rb:62:in `call'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/azure-storage-0.15.0.preview/lib/azure/storage/blob/block.rb:118:in `create_block_blob'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-azureblob-0.9.13-java/lib/logstash/inputs/azureblob.rb:479:in `save_registry'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-azureblob-0.9.13-java/lib/logstash/inputs/azureblob.rb:460:in `create_registry'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-azureblob-0.9.13-java/lib/logstash/inputs/azureblob.rb:357:in `register_for_read'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-azureblob-0.9.13-java/lib/logstash/inputs/azureblob.rb:165:in `process'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-azureblob-0.9.13-java/lib/logstash/inputs/azureblob.rb:151:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:409:in `inputworker'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:403:in `block in start_input'"] {:exception=>#<Azure::Core::Http::HTTPError:2010 @status_code: 412, @http_response: #<Azure::Core::Http::HttpResponse:0x285fc4c5 @http_response=#<Faraday::Response:0x41ed58fd @on_complete_callbacks=[], @env=#<Faraday::Env @method=:put @body="\xEF\xBB\xBF<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>LeaseLost</Code><Message>A lease ID was specified, but the lease for the blob has expired.\nRequestId:c3034529-001e-002c-0656-98c448000000\nTime:2018-12-20T11:24:10.5736280Z</Message></Error>" @url=#<URI::HTTPS https://*****.blob.core.windows.net/insights-logs-networksecuritygroupflowevent/data/registry> @request=#<Faraday::RequestOptions open_timeout=60> @request_headers={"User-Agent"=>"logstash-input-azureblob/0.9.11; Azure-Storage/0.15.0-preview (Ruby 2.3.3-p0; Linux linux)", "x-ms-date"=>"Thu, 20 Dec 2018 11:23:52 GMT", "x-ms-version"=>"2016-05-31", "DataServiceVersion"=>"1.0;NetFx", "MaxDataServiceVersion"=>"3.0;NetFx", "Content-Type"=>"application/atom+xml; charset=utf-8", "x-ms-blob-type"=>"BlockBlob", "x-ms-lease-id"=>"*****", "x-ms-blob-content-type"=>"text/plain; charset=UTF-8", "Content-Length"=>"100981", "Content-MD5"=>"*****", "Authorization"=>"SharedKey *****:*****"} @ssl=#<Faraday::SSLOptions verify=true> @response=#<Faraday::Response:0x41ed58fd ...> @response_headers={"content-length"=>"243", "content-type"=>"application/xml", "server"=>"Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0", "x-ms-request-id"=>"c3034529-001e-002c-0656-98c448000000", "x-ms-version"=>"2016-05-31", "date"=>"Thu, 20 Dec 2018 11:24:10 GMT", "connection"=>"close"} @status=412>>, @uri=#<URI::HTTPS https://*****.blob.core.windows.net/insights-logs-networksecuritygroupflowevent/data/registry>>, @uri: #<URI::HTTPS https://*****.blob.core.windows.net/insights-logs-networksecuritygroupflowevent/data/registry>, @description: "A lease ID was specified, but the lease for the blob has expired.\nRequestId:c3034529-001e-002c-0656-98c448000000\nTime:2018-12-20T11:24:10.5736280Z", @type: "LeaseLost">}
'''

Checking the data/registry lease it says "expired". I've tried acquiring and releasing the lease which puts it in "Available" state then restarting logstash.

Still no data comes through then checking the lease state of data/registry after a few minutes it says "Expired" again. However, the above error doesn't appear again - there's just no data being processed.

There is definitely new data in the blob storage.

Other things I've tried:

* deleting "data/registry". It gets re-created after restarting logstash but still no data processed
* reinstalling logstash-input-azureblob

Any assistance would be much appreciated!

Gen.

**Comment by GenCr** [comment]
I have now tried the following:
1. stopping logstash
2. deleting "data/registry"
3. uninstalling logstash-input-azureblob
4. installing logstash-input-azureblob
5. starting logstash

The "data/registry" file is no longer being recreated and no data is being processed.

Furthermore - within the same logstash pipeline and conf file I have another instance of azureblob input for a separate azure environment. This one also worked initially but today started working only intermittently. When I restart logstash, some data (from a few hours ago) gets processed but only up to the 59th minute of the hour. For example, I just restarted logstash now and events up to 13:59 (GMT+0) were processed. This pattern occurs ocassionaly when I restart logstash but they don't get processed automatically.

Please let me know if I can provide any other information that would help troubleshoot.

**Comment by GenCr** [comment]
Just to provide some updated information:

The plugin seems to work very intermittenly. The latest input instace that I mentioned previously is no longer processing data at all. However, the previous one has started processing data only when I restart logstash. For example, there is no steady stream of data but if I restart logstash any time after 12pm then it will process data up to 11.59am (but it would not do this without a logstash restart). I've run out of ideas of things to look at.

**Comment by GenCr** [comment]
Without any further intervention there were some events processed for one of the azure environments over the weekend but that stopped yesterday morning and now even if I restart logstash - no events are being processed. Instead I get the same error as I posted in my initial thread for both of the azure environments.

To me it seems that the plugin is having issues renewing/acquiring a new lease from Azure? The lease state of the /data/registry is currently "Available".

Still looking for assistance in solving this.

**Comment by MacFlurry** [comment]
same issue.
I think this plugin has trouble to renew a new lease when the lease expired:
```
    @body="\xEF\xBB\xBF<?xml version=\"1.0\" encoding=\"utf-8\"?>
               <Error>
                 <Code>
                   LeaseLost
                 </Code>
                   <Message>
                     A lease ID was specified, but the lease for the blob has expired.\n
                     RequestId:xxxxx-xxxx-xxxxx-xxxx-xxxxxxx\n
                     Time:2019-01-04T08:03:34.7429628Z
                   </Message>
                </Error>" 
```

**Comment by GenCr** [comment]
Thanks, I'll give it a go when I have some free time and report back!

**Comment by GenCr** [comment]
Where do you set the lease to 60?

**Comment by MacFlurry** [comment]
On your server, locate Azureblob.rb and in config section

**Comment by MacFlurry** [comment]
I also deleted the data/registry and set the registry_creation_policy to start_over before restarting

**Comment by GenCr** [comment]
Still nothing and no indication of where the problem is...

I've set the registry_create_policy to start_over and deleted the data/registry file from the blob. I then kicked in the logstash pipeline and commented out the other pipelines and restarted logstash.

The logs say the exact same thing as I posted in my previous comment.

Checked the data folder in Azure after restarting logstash and I can see the registry file was re-created but still no output to elastic search.

I've started to suspect that the problem occurs during outputting to elastic search so I've filtered out the elastic search output and added a stdout. The output there is pretty much the same with a few extra lines at the bottom:

> Jan 11 14:24:35 xxxxxxx logstash[84751]: [2019-01-11T14:24:35,572][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
Jan 11 14:25:37 xxxxxxx logstash[84751]: java.lang.OutOfMemoryError: Java heap space
Jan 11 14:25:37 xxxxxxx logstash[84751]: Dumping heap to java_pid84751.hprof ...
Jan 11 14:25:37 xxxxxxx logstash[84751]: Unable to create java_pid84751.hprof: Permission denied

**Comment by MacFlurry** [comment]
```
Jan 11 14:25:37 xxxxxxx logstash[84751]: java.lang.OutOfMemoryError: Java heap space
Jan 11 14:25:37 xxxxxxx logstash[84751]: Dumping heap to java_pid84751.hprof ...
```

increase the xms / xmx on your jvm.options on /etc/logstash
I recommend you to run the Logstash on a separate server.

**Comment by GenCr** [comment]
Looks like it was the java heap space. Surprising that it was failing to run with 1g though with nothing else on the server.

Logstash is already running on a separate server and outputting to a dedicated elasticsearch server.

I've set xms and xmg to 2g and it seems to be working now (not sure how stable it is yet though).

What's yours set to and how many pipelines are you running?

I've currently got 2 pipelines (NSG and azure event hubs pipeline for sign-in logs / audit logs) with 1 azure environment for NSG and 3 environments for event hubs. Not a lot of logs are going through these though but we are expecting to add more azure environments into the NSG pipeline.

Thanks a lot for your help!

**Comment by GenCr** [comment]
Do you mean I shouldn't specify "pipeline workers" in pipelines.yml? It was set to 3 for the NSG pipeline when we set it up so should I revert that?

The logstash server is running on 4gb memory and 2 cores.

**Comment by MacFlurry** [comment]
don't. let it choose itself for you according to the number of the Core.

**Comment by GenCr** [comment]
Gotcha, thanks!

**Comment by GenCr** [comment]
@MacFlurry is your one still working?

**Comment by MacFlurry** [comment]
I suspect this plugin is not working properly. the registry file becomes,  for some unknown reason, corrupt, the json parser complains of nonconforming entries.I am getting totally frustrated with it. I gave up.

**Comment by MacFlurry** [comment]
and the unjustifiable slowness, I won't even mention it.
