### ISSUE TITLE
Unknown setting 'file_tail_bytes' and 'file_head_bytes'

### ISSUE THREAD

**Issue by MOURIK** [Azure/azure-diagnostics-tools#183]
Hello,
I have a large amount of logs to process from blob storage to process with logstash that's why i tried to use "file_tail_bytes" and "file_head_bytes" settings but it doesn't works (Unknown setting). I want to know if it still supported by the plugin logtstash input azure blob ? and also if you an idea about this issue. 

**errors log:**
sudo ./bin/logstash -f /etc/logstash/conf.d/blob.conf --path.settings /etc/logstash
Sending Logstash logs to /var/log/logstash which is now configured via log4j2.properties
[2019-01-03T15:37:16,160][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2019-01-03T15:37:16,178][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"6.5.1"}
[2019-01-03T15:37:19,748][INFO ][logstash.inputs.azureblob] Using version 0.9.x input plugin 'azureblob'. This plugin should work but would benefit from use by folks like you. Please let us know if you find bugs or have suggestions on how to improve this plugin.
**[2019-01-03T15:37:19,759][ERROR][logstash.inputs.azureblob] Unknown setting 'file_tail_bytes' for azureblob**
**[2019-01-03T15:37:19,759][ERROR][logstash.inputs.azureblob] Unknown setting 'file_head_bytes' for azureblob**
[2019-01-03T15:37:19,766][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"LogStash::ConfigurationError", :message=>"Something is wrong with your configuration.", :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/config/mixin.rb:86:in `config_init'", "/usr/share/logstash/logstash-core/lib/logstash/inputs/base.rb:60:in `initialize'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-azureblob-0.9.7/lib/logstash/inputs/azureblob.rb:24:in `initialize'", "org/logstash/plugins/PluginFactoryExt.java:233:in `plugin'", "org/logstash/plugins/PluginFactoryExt.java:166:in `plugin'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:71:in `plugin'", "(eval):8:in `<eval>'", "org/jruby/RubyKernel.java:994:in `eval'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:49:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:90:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:42:in `block in execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:92:in `block in exclusive'", "org/jruby/ext/thread/Mutex.java:148:in `synchronize'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:92:in `exclusive'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:38:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:317:in `block in converge_state'"]}
[2019-01-03T15:37:20,029][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}

thank you in advance.

Hakim
[azure_blob.txt](https://github.com/Azure/azure-diagnostics-tools/files/2724697/azure_blob.txt)

**Comment by MOURIK** [comment]
When i use logstash-input-azureeventhub (0.9.8) i have the following error:

/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-azureblob-0.9.8/lib/logstash/inputs/azureblob.rb:81: warning: `-' after local variable or literal is interpreted as binary operator
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-azureblob-0.9.8/lib/logstash/inputs/azureblob.rb:81: warning: even though it seems like unary operator
