### ISSUE TITLE
Logstash container in AKS plugin problem

### ISSUE THREAD

**Issue by RamyNasrEldin** [Azure/azure-diagnostics-tools#187]
I am trying to use the plugin in logstash container in AKS cluster, I managed to add it to the image and it should be working to pull logs and diagnosis from service fabric storage accounts tables. 

I tried to read the pod logs to identify the problem and below is the only exception happens frequently

[WARN ][io.netty.channel.AbstractChannelHandlerContext] The exceptionCaught() event that was failed to submit was:
java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:821) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:327) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:320) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:746) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:317) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelIdle(IdleStateHandler.java:371) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.handler.timeout.IdleStateHandler$WriterIdleTimeoutTask.run(IdleStateHandler.java:529) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.handler.timeout.IdleStateHandler$AbstractIdleTask.run(IdleStateHandler.java:466) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:125) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

**Comment by brahmnes** [comment]
Hi @RamyNasrEldin ,

It's hard to tell what happened. From a quick search online, there are these threads that suggest you may have more than one logstash instance running?
https://github.com/elastic/logstash/issues/6279
https://github.com/deviantony/docker-elk/issues/251
