### ISSUE TITLE
Plugin error: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by Altiano** [Azure/azure-diagnostics-tools#200]
OS: Windows 10
ELK: 7.2.0

Installed using `logstash-plugint`

When running list

```
logstash-filter-xml
logstash-input-azure_event_hubs
**logstash-input-azureblob** <-- listed
logstash-input-beats
logstash-input-couchdb_changes
logstash-input-dead_letter_que
```

When execute the pipeline, got error:
```
[2019-07-15T11:10:23,545][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.2.0"}
[2019-07-15T11:10:31,033][ERROR][logstash.plugins.registry] Problems loading a plugin with {:type=>"input", :name=>"azureblob", :path=>"logstash/inputs/azureblob", :error_message=>"no implicit conversion of nil into String", :error_class=>TypeError, :error_backtrace=>["org/jruby/RubyKernel.java:989:in `require'", "D:/Elastic/logstash-7.2.0/vendor/bundle/jruby/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'", "D:/Elastic/logstash-7.2.0/vendor/bundle/jruby/2.5.0/gems/logstash-input-azureblob-0.9.13-java/lib/com/microsoft/json-parser.rb:3:in `<main>'", "org/jruby/RubyKernel.java:987:in `require'", "D:/Elastic/logstash-7.2.0/vendor/bundle/jruby/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'", "D:/Elastic/logstash-7.2.0/vendor/bundle/jruby/2.5.0/gems/logstash-input-azureblob-0.9.13-java/lib/logstash/inputs/azureblob.rb:1:in `<main>'", "org/jruby/RubyKernel.java:987:in `require'", "D:/Elastic/logstash-7.2.0/vendor/bundle/jruby/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'", "D:/Elastic/logstash-7.2.0/logstash-core/lib/logstash/plugins/registry.rb:191:in `legacy_lookup'", "D:/Elastic/logstash-7.2.0/logstash-core/lib/logstash/plugins/registry.rb:166:in `block in lookup'", "org/jruby/ext/thread/Mutex.java:165:in `synchronize'", "D:/Elastic/logstash-7.2.0/logstash-core/lib/logstash/plugins/registry.rb:162:in `lookup'", "D:/Elastic/logstash-7.2.0/logstash-core/lib/logstash/plugins/registry.rb:216:in `lookup_pipeline_plugin'", "D:/Elastic/logstash-7.2.0/logstash-core/lib/logstash/plugin.rb:143:in `lookup'", "org/logstash/plugins/PluginFactoryExt.java:203:in `plugin'", "org/logstash/plugins/PluginFactoryExt.java:120:in `buildInput'", "org/logstash/execution/JavaBasePipelineExt.java:50:in `initialize'", "D:/Elastic/logstash-7.2.0/logstash-core/lib/logstash/java_pipeline.rb:24:in `initialize'", "D:/Elastic/logstash-7.2.0/logstash-core/lib/logstash/pipeline_action/create.rb:36:in `execute'", "D:/Elastic/logstash-7.2.0/logstash-core/lib/logstash/agent.rb:325:in `block in converge_state'"]}
[2019-07-15T11:10:31,059][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"LogStash::PluginLoadingError", :message=>"Couldn't find any input plugin named 'azureblob'. Are you sure this is correct? Trying to load the azureblob input plugin resulted in this error: Problems loading the requested plugin named azureblob of type input. Error: TypeError no implicit conversion of nil into String", :backtrace=>["D:/Elastic/logstash-7.2.0/logstash-core/lib/logstash/plugins/registry.rb:221:in `lookup_pipeline_plugin'", "D:/Elastic/logstash-7.2.0/logstash-core/lib/logstash/plugin.rb:143:in `lookup'", "org/logstash/plugins/PluginFactoryExt.java:203:in `plugin'", "org/logstash/plugins/PluginFactoryExt.java:120:in `buildInput'", "org/logstash/execution/JavaBasePipelineExt.java:50:in `initialize'", "D:/Elastic/logstash-7.2.0/logstash-core/lib/logstash/java_pipeline.rb:24:in `initialize'", "D:/Elastic/logstash-7.2.0/logstash-core/lib/logstash/pipeline_action/create.rb:36:in `execute'", "D:/Elastic/logstash-7.2.0/logstash-core/lib/logstash/agent.rb:325:in `block in converge_state'"]}
```

Any idea?

**Comment by pgbconfirmit** [comment]
We are also having the same error. Did you ever find a fix?
What's strange is that the same config works fine in one Azure environment (Canada), but has this error in another (Germany).
