### ISSUE TITLE
Make logstash-input-azurewadtable plugin work with 2.3.X version of logstash

### ISSUE THREAD

**Issue by clintonm9** [Azure/azure-diagnostics-tools#4]
I noticed logstash-input-azurewadtable plugin README says it only supports 1.4.2 version of logstash. Can this be updated to support newer versions?

Trying this plugin on 2.3.1 and 2.2.4 this is the error i get (I am using CentOs 7):
```
Pipeline aborted due to error {:exception=>#<NameError: uninitialized constant Azure::TableService>, :backtrace=>["org/jruby/RubyModule.java:2745:in `const_missing'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-azurewadtable-0.9.5/lib/logstash/inputs/azurewadtable.rb:33:in `register'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:330:in `start_inputs'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:329:in `start_inputs'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:180:in `start_workers'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:136:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/agent.rb:465:in `start_pipeline'"], :level=>:error, :file=>"logstash/agent.rb", :line=>"467", :method=>"start_pipeline"}
```

Also, I wanted to let you know I had a very hard time getting this to work on 1.4.2. This is what I had before:
```
cat /etc/logstash/conf.d/logstash.conf 
input {
  azurewadtable {
    account_name => "xxxx"
    access_key => "xxx"
    table_name => "WADServiceFabricSystemEventTable"
    collection_start_time_utc => "2016-04-10T22:26:12-04:00"
  }
}
filter {
}
output {
elasticsearch {
                host => "localhost"
                protocol => "http"
        port => 9200
        }
}
/opt/logstash/bin/logstash -vv -f /etc/logstash/conf.d/logstash.conf 
.... lots of output ....

curl 'localhost:9200/_cat/indices?v'  
health status index    pri rep docs.count docs.deleted store.size pri.store.size 
yellow open   customer   5   1          1            0      3.6kb          3.6kb 
```

I could see the azure storage tables data in the debug, but nothing was going into elasticsearch. I didn't see any errors. I did install elasticsearch Version: 2.3.1.

I finally added index => "logstash" in the elasticsearch section of the logstash.conf file. This fixed my issue.

**Comment by clintonm9** [comment]
With version 0.9.6 this all works! Thanks
