### ISSUE TITLE
Logstash is stalled with the message as status=>"sleep" and not picking any file for processing from Azure Blob

### ISSUE THREAD

**Issue by nethis** [Azure/azure-diagnostics-tools#51]
I started facing an issue with logstash processing from Azure Blob. Logstsash keeps on running with no progress and not picking any file for processing from Azure Blob.

Below are the messages it continuously show. Could someone help here to resolve this issue and move ahead. 
```
{:timestamp=>"2016-11-22T10:38:59.842000+0000", :message=>"Flushing buffer at interval", :instance=>"#<LogStash::Outputs::ElasticSearch::Buffer:0xb23019a @operations_mutex=#<Mutex:0x5e4ee8e>, @max_size=500, @operations_lock=#<Java::JavaUtilConcurrentLocks::ReentrantLock:0x1db6aea>, @submit_proc=#<Proc:0x57651265@C:/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/common.rb:57>, @logger=#<Cabin::Channel:0x75d70699 @metrics=#<Cabin::Metrics:0x2f81aef3 @metrics_lock=#<Mutex:0x24f61bfa>, @metrics={}, @channel=#<Cabin::Channel:0x75d70699 ...>>, @subscriber_lock=#<Mutex:0x5bffc33b>, @level=:debug, @subscribers={13632=>#<Cabin::Subscriber:0x3485271c @output=#<Cabin::Outputs::IO:0x20b8c3bd @io=#<File:C:\\logstash-2.4.0\\logfiles\\customevent.log>, @lock=#<Mutex:0x5fb3a8a>>, @options={}>, 13634=>#<Cabin::Subscriber:0x1c1b2e5b @output=#<Cabin::Outputs::IO:0x1bb5703 @io=#<IO:fd 1>, @lock=#<Mutex:0x67f8d9a2>>, @options={:level=>:fatal}>}, @data={}>, @last_flush=2016-11-22 10:38:58 UTC, @flush_interval=1, @stopping=#<Concurrent::AtomicBoolean:0x7e270861>, @buffer=[], @flush_thread=#<Thread:0x25ff4be9 run>>", :interval=>1, :level=>:debug, :file=>"/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/buffer.rb", :line=>"90", :method=>"interval_flush"}
{:timestamp=>"2016-11-22T10:39:00.327000+0000", :message=>"Pushing flush onto pipeline", :level=>:debug, :file=>"/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb", :line=>"458", :method=>"flush"}
#<LogStash::PipelineReporter::Snapshot:0x3ab09a9 @data={:events_filtered=>0, :events_consumed=>0, :worker_count=>2, :inflight_count=>0, :worker_states=>[{:status=>"sleep", :alive=>true, :index=>0, :inflight_count=>0}, {:status=>"sleep", :alive=>true, :index=>1, :inflight_count=>0}], :output_info=>[{:type=>"elasticsearch", :config=>{"action"=>"index", "hosts"=>["10.158.36.220"], "codec"=>"json", "index"=>"customevent", "document_type"=>"dailyaggregate", "document_id"=>"%{dataid}", "__ALLOW_ENV__"=>false}, :is_multi_worker=>false, :events_received=>0, :workers=><Java::JavaUtilConcurrent::CopyOnWriteArrayList:-1286439783 [<LogStash::Outputs::ElasticSearch action=>"index", hosts=>["10.158.36.220"], codec=><LogStash::Codecs::JSON charset=>"UTF-8">, index=>"customevent", document_type=>"dailyaggregate", document_id=>"%{dataid}", workers=>1, manage_template=>true, template_name=>"logstash", template_overwrite=>false, flush_size=>500, idle_flush_time=>1, doc_as_upsert=>false, max_retries=>3, script_type=>"inline", script_var_name=>"event", scripted_upsert=>false, retry_max_interval=>2, retry_max_items=>500, retry_on_conflict=>1, ssl_certificate_verification=>true, sniffing=>false, sniffing_delay=>5>]>, :busy_workers=>0}], :thread_info=>[{"thread_id"=>19, "name"=>"[main]<azureblob", "plugin"=>nil, "backtrace"=>["[...]/vendor/bundle/jruby/1.9/gems/nokogiri-1.6.8-java/lib/nokogiri/xml/searchable.rb:157:in `new'", "[...]/vendor/bundle/jruby/1.9/gems/nokogiri-1.6.8-java/lib/nokogiri/xml/searchable.rb:157:in `xpath'", "[...]/vendor/bundle/jruby/1.9/gems/nokogiri-1.6.8-java/lib/nokogiri/xml/searchable.rb:156:in `map'", "[...]/vendor/bundle/jruby/1.9/gems/nokogiri-1.6.8-java/lib/nokogiri/xml/searchable.rb:156:in `xpath'", "[...]/vendor/bundle/jruby/1.9/gems/nokogiri-1.6.8-java/lib/nokogiri/xml/node.rb:115:in `>'", "[...]/vendor/bundle/jruby/1.9/gems/azure-0.7.6/lib/azure/blob/serialization.rb:159:in `blob_properties_from_xml'", "[...]/vendor/bundle/jruby/1.9/gems/azure-0.7.6/lib/azure/blob/serialization.rb:128:in `blob_from_xml'", "[...]/vendor/bundle/jruby/1.9/gems/azure-0.7.6/lib/azure/blob/blob.rb:23:in `initialize'", "[...]/vendor/bundle/jruby/1.9/gems/azure-0.7.6/lib/azure/blob/serialization.rb:124:in `blob_from_xml'", "[...]/vendor/bundle/jruby/1.9/gems/azure-0.7.6/lib/azure/blob/serialization.rb:112:in `blob_enumeration_results_from_xml'", "[...]/vendor/bundle/jruby/1.9/gems/nokogiri-1.6.8-java/lib/nokogiri/xml/node_set.rb:187:in `each'", "[...]/vendor/bundle/jruby/1.9/gems/nokogiri-1.6.8-java/lib/nokogiri/xml/node_set.rb:186:in `upto'", "[...]/vendor/bundle/jruby/1.9/gems/nokogiri-1.6.8-java/lib/nokogiri/xml/node_set.rb:186:in `each'", "[...]/vendor/bundle/jruby/1.9/gems/azure-0.7.6/lib/azure/blob/serialization.rb:111:in `blob_enumeration_results_from_xml'", "[...]/vendor/bundle/jruby/1.9/gems/azure-0.7.6/lib/azure/blob/blob_service.rb:378:in `list_blobs'", "[...]/vendor/bundle/jruby/1.9/gems/logstash-input-azureblob-0.9.5/lib/logstash/inputs/azureblob.rb:39:in `list_blob_names'", "[...]/vendor/bundle/jruby/1.9/gems/logstash-input-azureblob-0.9.5/lib/logstash/inputs/azureblob.rb:37:in `loop'", "[...]/vendor/bundle/jruby/1.9/gems/logstash-input-azureblob-0.9.5/lib/logstash/inputs/azureblob.rb:37:in `list_blob_names'", "[...]/vendor/bundle/jruby/1.9/gems/logstash-input-azureblob-0.9.5/lib/logstash/inputs/azureblob.rb:73:in `process'", "[...]/vendor/bundle/jruby/1.9/gems/logstash-input-azureblob-0.9.5/lib/logstash/inputs/azureblob.rb:89:in `run'", "[...]/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:342:in `inputworker'", "[...]/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:336:in `start_input'"], "blocked_on"=>nil, "status"=>"run", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/nokogiri-1.6.8-java/lib/nokogiri/xml/searchable.rb:157:in `new'"}, {"thread_id"=>23, "name"=>"[main]>worker0", "plugin"=>nil, "backtrace"=>["[...]/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:309:in `synchronize'", "[...]/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:309:in `inflight_batches_synchronize'", "[...]/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:234:in `worker_loop'", "[...]/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:201:in `start_workers'"], "blocked_on"=>nil, "status"=>"sleep", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:309:in `synchronize'"}, {"thread_id"=>24, "name"=>"[main]>worker1", "plugin"=>nil, "backtrace"=>["[...]/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:309:in `synchronize'", "[...]/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:309:in `inflight_batches_synchronize'", "[...]/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:234:in `worker_loop'", "[...]/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:201:in `start_workers'"], "blocked_on"=>nil, "status"=>"sleep", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:309:in `synchronize'"}], :stalling_threads_info=>[{"thread_id"=>19, "name"=>"[main]<azureblob", "plugin"=>nil, "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/nokogiri-1.6.8-java/lib/nokogiri/xml/searchable.rb:165:in `evaluate'"}, {"thread_id"=>23, "name"=>"[main]>worker0", "plugin"=>nil, "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:309:in `synchronize'"}, {"thread_id"=>24, "name"=>"[main]>worker1", "plugin"=>nil, "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:309:in `synchronize'"}]}>, :level=>:warn, :file=>"/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/shutdown_watcher.rb", :line=>"54", :method=>"start"}
```

**Comment by xiaomi7732** [comment]
Hi @nethis,
This should've been fixed in 0.9.8. Please refer https://rubygems.org/gems/logstash-input-azureblob.
