### ISSUE TITLE
Timeout putting on lease leads to infinite lease on registry lock file

### ISSUE THREAD

**Issue by xiaomi7732** [Azure/azure-diagnostics-tools#96]
Grab a call-stack:
```ruby
17:51:31.679 [[main]<azureblob] ERROR logstash.inputs.logstashinputazureblob - Oh My, An error occurred.
undefined method `type' for #<Faraday::TimeoutError>:
[
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-azureblob-0.9.10/lib/logstash/inputs/azureblob.rb:312:in `acquire_lease'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-azureblob-0.9.10/lib/logstash/inputs/azureblob.rb:310:in `acquire_lease'",
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-azureblob-0.9.10/lib/logstash/inputs/azureblob.rb:340:in `register_for_read'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-azureblob-0.9.10/lib/logstash/inputs/azureblob.rb:326:in `register_for_read'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-azureblob-0.9.10/lib/logstash/inputs/azureblob.rb:135:in `process'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-azureblob-0.9.10/lib/logstash/inputs/azureblob.rb:122:in `run'", 
"/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:456:in `inputworker'",
"/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:449:in `start_input'"] 
{:exception=>#<NoMethodError: undefined method `type' for #<Faraday::TimeoutError>>}
17:52:27.106 [[main]<azureblob] ERROR logstash.inputs.logstashinputazureblob - Oh My, An error occurred. LeaseAlreadyPresent (409): There is already a lease present.
RequestId:e502b8ce-001e-006a-3670-3163f3000000
Time:2017-09-19T17:52:27.0527018Z:
[
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/azure-core-0.1.12/lib/azure/core/http/retry_policy.rb:48:in `call'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/azure-core-0.1.12/lib/azure/core/http/http_request.rb:104:in `with_filter'", 
"org/jruby/RubyMethod.java:116:in `call'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/azure-core-0.1.12/lib/azure/core/http/signer_filter.rb:28:in `call'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/azure-core-0.1.12/lib/azure/core/http/http_request.rb:104:in `with_filter'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/azure-core-0.1.12/lib/azure/core/service.rb:36:in `call'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/azure-core-0.1.12/lib/azure/core/filtered_service.rb:34:in `call'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/azure-core-0.1.12/lib/azure/core/signed_service.rb:41:in `call'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/azure-storage-0.12.3.preview/lib/azure/storage/service/storage_service.rb:53:in `call'",
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/azure-storage-0.12.3.preview/lib/azure/storage/blob/blob_service.rb:59:in `call'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/azure-storage-0.12.3.preview/lib/azure/storage/blob/blob_service.rb:190:in `acquire_lease'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/azure-storage-0.12.3.preview/lib/azure/storage/blob/blob.rb:413:in `acquire_blob_lease'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-azureblob-0.9.10/lib/logstash/inputs/azureblob.rb:310:in `acquire_lease'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-azureblob-0.9.10/lib/logstash/inputs/azureblob.rb:340:in `register_for_read'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-azureblob-0.9.10/lib/logstash/inputs/azureblob.rb:326:in `register_for_read'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-azureblob-0.9.10/lib/logstash/inputs/azureblob.rb:135:in `process'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-azureblob-0.9.10/lib/logstash/inputs/azureblob.rb:122:in `run'", 
"/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:456:in `inputworker'", 
"/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:449:in `start_input'"] {:exception=>#<Azure::Core::Http::HTTPError:102053448 @status_code: 409, @http_response: #<Azure::Core::Http::HttpResponse:0x52946eb3 @http_response=#<Faraday::Response:0x9bf136a @on_complete_callbacks=[], @env=#<Faraday::Env @method=:put @body="\xEF\xBB\xBF<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>LeaseAlreadyPresent</Code><Message>There is already a lease present.\nRequestId:e502b8ce-001e-006a-3670-3163f3000000\nTime:2017-09-19T17:52:27.0527018Z</Message></Error>" @url=#<URI::HTTPS:0x648ff4b3 URL:https://saarslogstashtest001.blob.core.windows.net/wad-iis-logfiles/data/registry.lock?comp=lease&timeout=10> @request=#<Faraday::RequestOptions open_timeout=60> @request_headers={"User-Agent"=>"Azure-Storage/0.12.3-preview (Ruby 1.9.3-p551; Linux linux)", "x-ms-date"=>"Tue, 19 Sep 2017 17:52:26 GMT", "x-ms-version"=>"2015-04-05", "DataServiceVersion"=>"1.0;NetFx", "MaxDataServiceVersion"=>"3.0;NetFx", "Content-Type"=>"application/atom+xml; charset=utf-8", "x-ms-lease-action"=>"acquire", "x-ms-lease-duration"=>"-1", "Content-Length"=>"0", "Authorization"=>"SharedKey saarslogstashtest001:uh6+vk4OBALABALA="} @ssl=#<Faraday::SSLOptions verify=true> @response=#<Faraday::Response:0x9bf136a ...> @response_headers={"content-length"=>"221", "content-type"=>"application/xml", "server"=>"Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0", "x-ms-request-id"=>"e502b8ce-001e-006a-3670-3163f3000000", "x-ms-version"=>"2015-04-05", "date"=>"Tue, 19 Sep 2017 17:52:26 GMT", "connection"=>"close"} @status=409>>, @uri=#<URI::HTTPS:0x26632dee URL:https://saarslogstashtest001.blob.core.windows.net/wad-iis-logfiles/data/registry.lock?comp=lease&timeout=10>>, @uri: #<URI::HTTPS:0x26632dee URL:https://saarslogstashtest001.blob.core.windows.net/wad-iis-logfiles/data/registry.lock?comp=lease&timeout=10>, @description: "There is already a lease present.\nRequestId:e502b8ce-001e-006a-3670-3163f3000000\nTime:2017-09-19T17:52:27.0527018Z", @type: "LeaseAlreadyPresent">}
17:53:22.427 [[main]<azureblob] ERROR logstash.inputs.logstashinputazureblob - Oh My, An error occurred. LeaseAlreadyPresent (409): There is already a lease present.
```
There are 2 problems:
1. The exception handling of checking type property on error is causing yet another exception.
2. Somehow, after the timeout exception is thrown, the lease is still put on to the file, thus leads to infinite lease, which seems like a ruby storage SDK bug.

**Comment by xiaomi7732** [comment]
Fixed and released at: https://rubygems.org/gems/logstash-input-azureblob/versions/0.9.11
